version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - echo $FIREBASE_CONFIG_BASE64 | base64 --decode > serviceAccount.json
      - ls -lah

  post_build:
    commands:
      - echo "Packaging application..."
      - zip -r deploy-package.zip .  # Zip everything
      # Copy to the exact same location that worked
      - aws s3 cp deploy-package.zip s3://hpdoc/deploy-package.zip



artifacts:
  files:
    - package.json
    - package-lock.json
    - .env
    - config/**/*
    - controllers/**/*
    - helpers/**/*
    - models/**/*
    - public/**/*
    - routes/**/*
    - views/**/*
    - server.js
    - appspec.yml
    - scripts/**/*
  base-directory: '.'  # Use the root directory
  name: deploy-package.zip  # Use the same name