version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - echo $FIREBASE_CONFIG_BASE64 | base64 --decode > serviceAccountKey.json
      - ls -lah

  post_build:
    commands:
      - echo "Preparing for deployment..."
      - cp -r scripts/ ./scripts/
      - cp appspec.yml ./
      # Still keep your S3 backup if desired
      - aws s3 cp deploy-package.zip s3://hpdoc/

artifacts:
  files:
    - package.json
    - package-lock.json
    - .env
    - config/**/*
    - controllers/**/*
    - helpers/**/*
    - models/**/*
    - public/**/*
    - routes/**/*
    - views/**/*
    - server.js
    - appspec.yml
    - scripts/**/*
  base-directory: '.'