version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building application..."
      - npm run build
  post_build:
    commands:
      - echo "Zipping artifact..."
      - zip -r deploy-package.zip .  

artifacts:
  files:
    - deploy-package.zip
  discard-paths: no
  name: deploy-package  # Force the artifact to have a static name
