version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo No build step required for this application...
  post_build:
    commands:
      - echo Deployment package preparation completed on `date`

artifacts:
  files:
    - package.json
    - package-lock.json
    - .env
    - config/**/*
    - controllers/**/*
    - helpers/**/*
    - models/**/*
    - public/**/*
    - routes/**/*
    - views/**/*
    - server.js
    - appspec.yml
    - serviceAccountKey.json
    - scripts/**/*
  base-directory: '.'