version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - echo $FIREBASE_CONFIG_BASE64 | base64 --decode > serviceAccount.json
      - ls -lah  # Verify the file exists
      - cat serviceAccount.json  # Debugging: remove this in production

  post_build:
    commands:
      - echo "Preparing deployment package..."
      - zip -r deploy-package.zip .  # Zip project for deployment
      - aws s3 cp deploy-package.zip s3://hpdoc/

artifacts:
  files:
    - deploy-package.zip
  discard-paths: yes
