version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Building application..."
      - zip -r deploy-package.zip .  # Create deployment package 1
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deploy-package.zip s3://hpdoc/deploy-package.zip
artifacts:
  files:
    - deploy-package.zip
  discard-paths: yes
