version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "No build step required for this application..."

  post_build:
    commands:
      - echo "Preparing for deployment..."
      - zip -r deploy-package.zip .  # Zips the entire project for deployment

artifacts:
  files:
    - deploy-package.zip
  discard-paths: yes
